# Generated by Django 6.0.7 on 2026-08-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('POS', '0004_supplier_address_supplier_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='GCash Reference Number', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Gcash', 'GCash'), ('Utang', 'Utang')], default='Cash', max_length=50),
        ),
    ]
